name: Release

on:
  workflow_dispatch:
    inputs:
      f3d_version:
        description: 'F3D version to build'
        required: true
        default: '1.3.1'

jobs:
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}
    container: ${{ matrix.os == 'ubuntu-latest' && 'ghcr.io/f3d-app/f3d-ci' || null }}

    env:
      DISPLAY: :0

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'source'
        submodules: 'true'
        lfs: 'true'
        ref: v${{ github.event.inputs.f3d_version}}

    - name: Build and package F3D
      uses: ./source/.github/actions/f3d-superbuild/
      with:
        f3d_version: ${{github.event.inputs.f3d_version}}
        os: ${{matrix.os}}
